### ISSUE TITLE
Slick Magnified Image Issues

### ISSUE THREAD

**Issue by p-rk** [ethanselzer/react-image-magnify#45]
Hi,
Thanks for the awesome library. I'm facing some issue with the magnified image. Please check the screenshots. The magnified image is getting white space instead it should be fixed and the whole image inside the container moving.

Hover on top left corner on image works proper but when i try to move on the image the magnified image also moves.

![screen shot 2018-09-03 at 12 45 29 pm](https://user-images.githubusercontent.com/30556391/44972735-e0114f80-af77-11e8-8725-7558aaf10223.png)
![screen shot 2018-09-03 at 12 45 47 pm](https://user-images.githubusercontent.com/30556391/44972737-e273a980-af77-11e8-96d1-85fa3c488cbb.png)
![screen shot 2018-09-03 at 12 46 00 pm](https://user-images.githubusercontent.com/30556391/44972742-e43d6d00-af77-11e8-9861-f19669372824.png)

**Comment by p-rk** [comment]
The issue is with my global CSS which has max-width and border for an image tag.

**Comment by yc-codes** [comment]
If you're using tailwind and facing this issue,

I added these lines and it’s working fine

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
   /* ... */

    .react-slick img,
    .slick-slide img {
        max-width: unset;
    }
}
```
